import localFont from "next/font/local";
import "./globals.css";
import {Outfit} from "next/dist/compiled/@next/font/dist/google";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const outfit = localFont({
    src: "./fonts/outfit.ttf",
    variable: "--font-outfit",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});
const AudioNugget = localFont({
    src: "./fonts/AudioNugget.ttf",
    variable: "--font-audio-nugget",
    weight: "100 900",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} ${AudioNugget.variable} ${outfit.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
